name: End-toend tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install npm dpencenciaes, cache them correctly
        # and run all cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6